spring.application.name=gerenciador-api
# Configuração de conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/gerenciador_bd
spring.datasource.username=admin
spring.datasource.password=123

# Configuração do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true